//PRODUCTOS
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const OBTENER_PRODUCTOS_FILTRADOS = 'OBTENER_PRODUCTOS_FILTRADOS';
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';

//USUARIOS
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';

//VENTAS
export const OBTENER_VENTAS = 'OBTENER_VENTAS';
export const OBTENER_VENTAS_FILTRADAS = 'OBTENER_VENTAS_FILTRADAS';
export const AGREGAR_VENTA = 'AGREGAR_VENTA';
export const EDITAR_VENTA = 'EDITAR_VENTA';

//ALERTAS
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const CERRAR_ALERTA = 'CERRAR_ALERTA';

//AUTH
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const CERRAR_SESION = 'CERRAR_SESION';