//PRODUCTOS
export const LISTANDO_PRODUCTO = 'LISTANDO_PRODUCTO';
export const CREANDO_PRODUCTO = 'CREANDO_PRODUCTO';
export const EDITANDO_PRODUCTO = 'EDITANDO_PRODUCTO';
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const OBTENER_PRODUCTOS_FILTRADOS = 'OBTENER_PRODUCTOS_FILTRADOS';
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';

//USUARIOS
export const LISTANDO_USUARIO = 'LISTANDO_USUARIO';
export const EDITANDO_USUARIO = 'EDITANDO_USUARIO';
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const SELECCIONAR_USUARIO = 'SELECCIONAR_USUARIO';

//VENTAS
export const LISTANDO_VENTA = 'LISTANDO_VENTA';
export const CREANDO_VENTA = 'CREANDO_VENTA';
export const EDITANDO_VENTA = 'EDITANDO_VENTA';
export const OBTENER_VENTAS = 'OBTENER_VENTAS';
export const OBTENER_VENTAS_FILTRADAS = 'OBTENER_VENTAS_FILTRADAS';
export const AGREGAR_VENTA = 'AGREGAR_VENTA';
export const EDITAR_VENTA = 'EDITAR_VENTA';
export const SELECCIONAR_VENTA = 'SELECCIONAR_VENTA';

//ALERTAS
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const CERRAR_ALERTA = 'CERRAR_ALERTA';

//AUTH
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const CERRAR_SESION = 'CERRAR_SESION';